"""Print the sudo rules this dashboard needs — exactly, and nothing more.

The list comes from the service catalogue, so it can never drift from what the buttons
actually do. deploy/install.sh writes the output to /etc/sudoers.d/ after checking it.
"""

from django.core.management.base import BaseCommand

from pidash.services.catalog import services
from pidash.services.systemd import ACTIONS, SYSTEMCTL


def rules() -> list[str]:
    commands = []
    for service in services():
        for action in ACTIONS:  # start, stop, restart
            commands.append(f"{SYSTEMCTL} {action} {service.control_unit}")
        for run in service.runs:
            commands.append(f"{SYSTEMCTL} start {service.run_unit(run.mode)}")
    commands += [f"{SYSTEMCTL} reboot", f"{SYSTEMCTL} poweroff"]
    # Keep it stable and free of duplicates so the file only changes when the config does.
    return sorted(set(commands))


class Command(BaseCommand):
    help = "Print the sudoers rules for the account the dashboard runs as."

    def add_arguments(self, parser):
        parser.add_argument("--user", default="pidash", help="The account that runs the dashboard")

    def handle(self, *args, user: str, **options):
        self.stdout.write(f"# Generated by `manage.py print_sudoers` — {len(rules())} commands.")
        self.stdout.write("# The dashboard may control these units and nothing else.")
        self.stdout.write(f"{user} ALL=(root) NOPASSWD: " + ", \\\n    ".join(rules()))
