# Generated by Django 5.2.17 on 2026-09-24 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("service_id", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("raised_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notified", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["service_id"],
            },
        ),
    ]
